### ISSUE TITLE
Generic type 'ɵɵDirectiveDeclaration' requires between 6 and 8 type arguments.

### ISSUE THREAD

**Issue by dancornilov** [angular-magic/ngx-gp-autocomplete#1]
**In case if you have this problem:**

![Screenshot 2023-02-22 at 10 35 54](https://user-images.githubusercontent.com/24212761/220566173-4754b83c-5e5e-4ca1-93d7-cb939d12f357.png)

**This is solution:**
_tsconfig.json_
```
{
    ...
    complilerOptions: {
        ...
        "skipLibCheck": true
    }
}
```

**Comment by fetwar** [comment]
Is there no way to resolve this without editing project wide configuration files?
Even something as simple as `// @ts-ignore`?

p.s. thanks for a nice module!
