### ISSUE TITLE
DirectiveDeclaration constraint issues

### ISSUE THREAD

**Issue by DrHazi** [angular-magic/ngx-gp-autocomplete#12]
Hi I have implemented all of the code steps and all required modules for the autocomplete.
I have removed the options out of the html input tag.
After all these steps I noticed that the actual module is having assignment issues see attached image.

Please advise what to do regarding this. As I am really struggling to find a google places autocomplete that works for my project.

Thanks in advance.
![test](https://github.com/angular-magic/ngx-gp-autocomplete/assets/53636877/31a24427-01c4-4502-bd4f-fc0caab244c5)

**Comment by dancornilov** [comment]
Hey, hopefully our package helped you in your project, as you can see here in [default example,](https://github.com/angular-magic/ngx-gp-autocomplete/blob/main/src/app/autocomplete-examples/pages/default-autocomplete/default-autocomplete.component.html) directive works well without passing some `[options]`. 
Will be easier for us to understand a resolve problem _(in case if problem persist)_ if you can provide a simple project where you can reproduce this error.

---

But before that ensure that you did this actions

1. Install our package `npm i @angular-magic/ngx-gp-autocomplete@latest`
2. Import in your our module `NgxGpAutocompleteModule` in your `AppModule` -> `imports`
3. Provide `Loader` in `AppModule` -> `providers`
```
{
      provide: Loader,
      useValue: new Loader({
        apiKey: YOUR_API_KEY,
        libraries: ['places'],
      }),
}
```
_NB: Replace this string `YOUR_API_KEY` with your api key from google console._
4. Use our directive to your input
```
<input #ngxPlaces="ngx-places"
                 class="input"
                 type="text"
                 ngx-gp-autocomplete />
```
---
In case if this doesn't help you try tot git clone this repository and run it locally, in case if in this repository functionality will work like expected, try to find difference between this project and your.

**Comment by dancornilov** [comment]
Because of inactivity this issue is closed.
