### ISSUE TITLE
Suggestion : Use different Google Maps API loader (check if api is already loaded)

### ISSUE THREAD

**Issue by finoanamendrika** [angular-magic/ngx-gp-autocomplete#14]
Hi,

Thank you for this great library.
I am working with this lib on a work project.The lib has his built-in API loader, and it makes the lib more independent. But there is ick when we want to use this lib with another Google Maps API based libraries due to API loading conflict issue.

So I want to suggest a supplementary test that at first, check if the API is already loaded `this.isGoogleLibExists()` and then decide to load or not the API using `this.loader.importLibrary()` function.

That will be helpful.

Thank you!

**Comment by dancornilov** [comment]
Hey,
I'm glad to hear that this package can help you solve your problems. The check you mentioned was added in version **2.0.1** Please upgrade your package and let me know if you encounter any troubles or errors.

Thanks in advance!

**Comment by dancornilov** [comment]
An issue was identified after adding this check by default, this is why now this check you can configure by yourself by enabling this check from `NgxGpAutocompleteService`. This change is available in `2.0.2`.

```
constructor(private ngxGpAutocompleteService :NgxGpAutocompleteService) {
  this.ngxGpAutocompleteService.enableGooglePersistenceCheck();
}
```

**Comment by finoanamendrika** [comment]
Hi,

Thank your for this update, It will be helpful for me and maybe for someone else. I will get you in touch ASAP.

**Comment by mendrikarabeh** [comment]
Hi,

I upgraded the package to `2.0.2` and now I the app won't run anymore :) Do you have any idea?

 "@angular/core": "^15.2.9",
 "tslib": "^2.3.0",
 
 
![image](https://github.com/angular-magic/ngx-gp-autocomplete/assets/126238275/68f58263-e507-4215-8392-d0c6d38712b2)
