### ISSUE TITLE
Property '"options"' is incompatible with index signature.

### ISSUE THREAD

**Issue by tehsiawtian** [angular-magic/ngx-gp-autocomplete#16]
![image](https://github.com/angular-magic/ngx-gp-autocomplete/assets/105415940/93f3aa6d-e3ea-4097-905a-77d0ab7ea2d3)

Hii currently I am using Angular 15, and facing this error after follow the instructions that you given to install this package.

**Comment by dancornilov** [comment]
Hey, maybe you can find answer in this issue?
https://github.com/angular-magic/ngx-gp-autocomplete/issues/1
