### ISSUE TITLE
OnHandleAddressChange not fired after updated to 2.0.1

### ISSUE THREAD

**Issue by brunbimmer** [angular-magic/ngx-gp-autocomplete#18]
Anyone observe the issue with the "OnAddressChange" with the updates? After pulling in 2.0.1, I noticed that our address options stopped being pre-filled. When I forced-moved back to 2.0.0, it started working again?

Anyone able to comment!?!

**Comment by dancornilov** [comment]
Hello, please use `2.0.2` version, probably this issue will not be reproducible.
