### ISSUE TITLE
App won't start: May be typescript issue

### ISSUE THREAD

**Issue by mendrikarabeh** [angular-magic/ngx-gp-autocomplete#19]
Hi,

I upgraded the package to `2.0.2` and now I the app won't run anymore :) Do you have any idea?

 "@angular/core": "^15.2.9",
 "tslib": "^2.3.0",
 
 
![image](https://github.com/angular-magic/ngx-gp-autocomplete/assets/126238275/68f58263-e507-4215-8392-d0c6d38712b2)

_Originally posted by @mendrikarabeh in https://github.com/angular-magic/ngx-gp-autocomplete/issues/14#issuecomment-2012140227_

**Comment by dancornilov** [comment]
Hello, as I mentioned [here](https://github.com/angular-magic/ngx-gp-autocomplete/issues/14#issuecomment-1966345804), if you use `2.0.2` you need to enable google persistance check by yourself.

**Comment by saiyajinu** [comment]
I am currently having the same issue, any fixes found?

**Comment by dancornilov** [comment]
Hey @saiyajinu, have you tried installing the latest version, which is `2.0.2`? Try to provide more details on how to reproduce this issue. Currently, I'm using `2.0.2` in my Angular 17 project and everything works as expected.

**Comment by saiyajinu** [comment]
I am using angular 15 so i guess that might be the starting problem. Yes i did install the latest version, aswell as the other two packages needed, i have imported the module and did added the provider and then I get the following compiling error: `Error: node_modules/@angular-magic/ngx-gp-autocomplete/lib/ngx-gp-autocomplete.directive.d.ts:24:113 - error TS2344: Type '{ options: { alias: "options"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
[ng]   Property '"options"' is incompatible with index signature.
[ng]     Type '{ alias: "options"; required: false; }' is not assignable to type 'string'.
[ng] 
[ng] 24     static ɵdir: i0.ɵɵDirectiveDeclaration<NgxGpAutocompleteDirective, "[ngx-gp-autocomplete]", ["ngx-places"], { "options": { "alias": "options"; "required": false; }; }, { "onAddressChange": "onAddressChange"; }, never, never, false, never>;`
which seems to be the same as the one of the guy that opened the issue.
Also while writing this comment i noticed he has angular 15 aswell. Is there any workaround for this that doesn't need updating the angular version?

**Comment by dancornilov** [comment]
You checked this [issue](https://github.com/angular-magic/ngx-gp-autocomplete/issues/1), maybe adjusting of this configuration can help.

**Comment by saiyajinu** [comment]
> You checked this [issue](https://github.com/angular-magic/ngx-gp-autocomplete/issues/1), maybe adjusting of this configuration can help.

Yes it works, now it compiles, thank you!
