### ISSUE TITLE
Geometry -> location (lat and lng) are empty

### ISSUE THREAD

**Issue by RomanZakharchuk** [angular-magic/ngx-gp-autocomplete#20]
<img width="516" alt="Screenshot 2024-05-09 at 11 26 20" src="https://github.com/angular-magic/ngx-gp-autocomplete/assets/70903505/c4b906ca-4bbe-4156-b5e3-c2fdf03e5ac1">

**Comment by dancornilov** [comment]
Hey, this response is returned by Google services, we can not change something.
