### ISSUE TITLE
The autocomplete popups don't get destroyed...

### ISSUE THREAD

**Issue by IslombekHasan** [angular-magic/ngx-gp-autocomplete#4]
On focus out or error, they are still on the screen. 
![image](https://github.com/angular-magic/ngx-gp-autocomplete/assets/33321034/58adcde5-bf7c-4601-bd9f-0a58c66b81ed)

**Comment by dancornilov** [comment]
Hey, thank you for your time. I have identified the issue, and it is associated with the Google Console configuration. If you use your own key, this problem should not occur.

<img width="1329" alt="Screenshot 2023-06-19 at 10 48 57" src="https://github.com/angular-magic/ngx-gp-autocomplete/assets/24212761/b93b614d-9cec-49eb-89aa-ad56081a80e1">
