### ISSUE TITLE
not working when having a loader

### ISSUE THREAD

**Issue by runtimebug** [angular-magic/ngx-gp-autocomplete#9]
I already had a google maps loader in my project which would cause an error. using a singleton loader and inject it is the way to go here. 

When can we expect an update? Thank you in advance!

**Comment by dancornilov** [comment]
Hey, thank you for using our packages, it's already available in version `2.0.0`.

**Comment by runtimebug** [comment]
Thank you for the update!
Please update the readme to remove the API key:
<img width="852" alt="image" src="https://github.com/angular-magic/ngx-gp-autocomplete/assets/23739454/1eded7c8-b056-49b3-8b93-eb1a40632d67">
